<a href="https://colab.research.google.com/github/Mamdouh4785/my-projects/blob/main/Stc-Moana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

file_path = "stc TV Data Set_T3.xlsx"
df = pd.read_excel(file_path)

display(df.head())

,Unnamed: 0,user_id_maped,program_name,rating,date_,program_genre
0,0,26138,100 treets,1,2017-05-27,Drama
1,1,7946,Moana,1,2017-05-21,Animation
2,2,7418,The Mermaid Princess,1,2017-08-10,Animation
3,3,19307,The Mermaid Princess,2,2017-07-26,Animation
4,4,15860,Churchill,2,2017-07-07,Biography

In [2]:
user_item_matrix = df.groupby(['user_id_maped', 'program_name'])['rating'].max().unstack()

In [3]:
moana_ratings = user_item_matrix['Moana']
similar_to_moana = user_item_matrix.corrwith(moana_ratings)

corr_moana = pd.DataFrame(similar_to_moana, columns=['Correlation']).dropna()

ratings_count = df.groupby('program_name')['rating'].count()
corr_moana = corr_moana.join(ratings_count.rename('ratings_count'))

Top 5 recommendations for users who watched the movie "Moana"

In [4]:
top_5_recommendations = corr_moana[corr_moana['ratings_count'] > 500].sort_values(by='Correlation', ascending=False)

display(top_5_recommendations.iloc[1:6])

                                        Correlation  ratings_count
program_name
Alvin and the Chipmunks: The queakquel     0.474710           1118
Ferdinand                                  0.384529           6817
Trolls                                     0.381701          13793
The Boss Baby                              0.364928          24047
Lego cooby-Doo! Blowout Beach Bash         0.355143            701